added other test validations
anusianne/pp_workshop pull request #5
Opened 2024-06-27 18:10 UTC by anusianne

2024-07-01 18:11 UTC, IsoldeFair requested changes
niestety, czasem te testy failują, proszę znajdź powód i napraw go :)

2024-07-01 18:11 UTC, IsoldeFair commented on db/seeds.rb
> +    Article.create(title: Faker::Book.title, body: Faker::Lorem.sentence(word_count: 3), published: Faker::Boolean.boolean)
użyj proszę tutaj FactoryBota :)

2024-07-01 18:39 UTC, anusianne commented on db/seeds.rb
> +    Article.create(title: Faker::Book.title, body: Faker::Lorem.sentence(word_count: 3), published: Faker::Boolean.boolean)
ok 👍🏼

2024-07-02 09:28 UTC, IsoldeFair approved these changes
pięknie! 🔥

2024-07-02 12:45 UTC, merged